image: rocker/tidyverse

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'

stages:
  - build

deployment:
  stage: build
  variables:
    SECURE_FILES_DOWNLOAD_PATH: './'
  script:
    - COPY .Renviron ./.Renviron
    - R -e 'source("./install.R", chdir= TRUE)'
    - R -e 'source("./init.R", chdir = TRUE)'
