copy:
  stage: build
  script:
    - echo $PW | sudo cp -r ./install.R /srv/Methodenbot/telegramBot/install.R
    - echo $PW | sudo cp -r ./init.R /srv/Methodenbot/telegramBot/init.R
    - echo $PW | sudo cp -r ./texts/* /srv/Methodenbot/telegramBot/texts/
    - echo $PW | sudo cp -r ./keys/* /srv/Methodenbot/telegramBot/keys/
    - echo $PW | sudo cp -r ./.Renviron /srv/Methodenbot/telegramBot/.Renviron
    - echo $PW | sudo cp -r ./Dockerfile /srv/Methodenbot/Dockerfile
  tags:
    - update

stop:
  stage: build
  script:
    - echo $PW | sudo -S  docker stop $(docker ps -q --filter ancestor=kleer/methodenbot )
  tags: 
    - update

docker:
  stage: deploy
  script:
    - cd /srv/Methodenbot
    - sudo docker build -t kleer/methodenbot .
  tags:
    - update

start:
  stage: deploy
  script:
    - cd /srv/Methodenbot
    - sudo docker run --rm kleer/methodenbot
  timeout: 0h 5m
  tags:
    - update

