image: rocker/tidyverse

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'

stages:
  - build

deployment:
  stage: build
  script:
    - COPY .Renviron /root/.Renviron
    - R -e 'source("./install.R", chdir = TRUE)'
    - R -e 'source("./init.R", chdir = TRUE)'
