before_script:
  - cd /srv/Methodenbot

copy:
  stage: build
  script:
    - sudo cp -r ./install.R /svr/Methodenbot/telegramBot/install.R
    - sudo cp -r ./init.R /svr/Methodenbot/telegramBot/init.R
    - sudo cp -r ./texts/* /svr/Methodenbot/telegramBot/texts/*
    - sudo cp -r ./keys/* /svr/Methodenbot/telegramBot/keys/*
    - sudo cp -r ./.Renviron /svr/Methodenbot/telegramBot/.Renviron
    - sudo cp -r ./Dockerfile /svr/Methodenbot/Dockerfile
