copy:
  stage: build
  script:
    - sudo cp -r ./install.R /srv/Methodenbot/telegramBot/install.R
    - sudo cp -r ./init.R /srv/Methodenbot/telegramBot/init.R
    - sudo cp -r ./texts/* /srv/Methodenbot/telegramBot/texts/
    - sudo cp -r ./keys/* /srv/Methodenbot/telegramBot/keys/
    - sudo cp -r ./.Renviron /srv/Methodenbot/telegramBot/.Renviron
    - sudo cp -r ./Dockerfile /srv/Methodenbot/Dockerfile

stop:
  stage: build
  script:
    - echo $PW | sudo -S  docker stop $(docker ps -q --filter ancestor=kleer/methodenbot )

docker:
  stage: deploy
  script:
    - cd /srv/Methodenbot
    - sudo docker build -t kleer/methodenbot .

start:
  stage: deploy
  script:
    - cd /srv/Methodenbot
    - sudo docker run --rm kleer/methodenbot
  after_script:
  - echo cleaning now

